name: 'Run Self Test'

on:
  workflow_dispatch:

jobs:
  test:
    name: Test GitHub Action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: 'Self Test'
        uses: ./
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
